### ISSUE TITLE
Versioning system

### ISSUE THREAD

**Issue by roG0d** [PRQL/homebrew-prql#1]
Through **GitHub Actions**, create a **workflow** that enables to keeps **updated** the formula with the latest stable release.

The solution would go as:

1. A new release on `prql/prql` is made ---> Trigger a workflow `on: release` that sends a `workflow_dispatch`.
 2. on `prql/homebrew-prql` ---> There's a workflow listening for the `workflow_dispatch` event. this workflow would change the .tar URL and the version from the Formula

**Comment by roG0d** [comment]
For now, It's working just the beginning of the solution:

- Its has been created a fork of prql/prql on [rog0d/prql](https://github.com/roG0d/prql/). This fork will serve as a testing ground for publishing releases and testing with the workflows
- The workflow [release.yml](https://github.com/roG0d/prql/blob/main/.github/workflows/release1.yml) has been created. It generates a `workflow_dispatch` that will activate the brew workflow on `prql/homebrew-prql` every **release**.
- The workflow [update.yml](https://github.com/prql/homebrew-prql/blob/actions/.github/workflows/update.yml) has been created. It gets activated with the previous `workflow_dispatch` and show a simple testing echo

**Comment by roG0d** [comment]
The version and URL inputs are working fine between workflows:
- It has been added an input parameter on the [release.yml](https://github.com/roG0d/prql/blob/main/.github/workflows/release.yml) containing the **version** of the release and the **URL** of the .tar. This is obtained via the `${{ github.ref }}` enviroment variable which give us the /refs/tags/*tag* of the release that triggers the workflow
- In the workflow [update.yml](https://github.com/prql/homebrew-prql/blob/actions/.github/workflows/update.yml), it has been added everything needed for the inputs to get working (**inputs and descriptions of the same**). Lately, It is **tested** via some dummy echo containing the version and the URL as it can be seen on the [_Actions Tab_ ](https://github.com/prql/homebrew-prql/runs/6270916448?check_suite_focus=true)
- **CAREFUL** the current URL is already pointing to the original [prql](https://github.com/prql/prql) repo, not to the testing [one](https://github.com/roG0d/prql), which has no .tar assets on its testing releases

**Comment by roG0d** [comment]
The version and URL tags are **commited** to prql.rb as expected:

- The [update.yml](https://github.com/prql/homebrew-prql/blob/actions/.github/workflows/update.yml) file has 2 jobs:
	- **edit-tags**: Responsible of editing the tags to match the proper syntax (ej: version "0.1.2").
	- **commit-tags**: Based on actions/checkout@v3. Responsible of adding double quotations to the variables, use sed for the prql.rb file to change the tags (URL and version) and to commit the propers changes

For now, there's a **bug** on the [release.yml](https://github.com/roG0d/prql/blob/main/.github/workflows/release.yml) that triggers 4 workflows on the prql repo. Even with this bug, update.yml behaves **works properly** as no change is performed on the prql.rb file.

**Comment by roG0d** [comment]
The SHA256 is a field to be updated too, this has been achieved on commit c830e2a6e5a2bfe2d88c6531e968cd610f462312
The idea for this has been:

- The SHA 256 contains the checksum of the .tar.gz containing the source files of the proyect. So it's needed to download those via the `${{ needs.edit-tag.outputs.url }}`: `wget ${{ needs.edit-tag.outputs.url }}`. It's used `${{ needs.edit-tag.outputs.url }}`. because it doesn´t contains double quotes (necessaries on the formulae field). If not it would result in a scheme error.
- Now the checksum value it's needed, so the shasum function is used as it follows:`export SHA=$(shasum -a 256 ${{ needs.edit-tag.outputs.tag }}.tar.gz)`
- It's needed to split the result of the shasum command, so:  `export SHA=$(echo $SHA | cut -f 1  -d ' ')`
- Lastly the formulae is updated via the sed command: `sed -i "5 s/sha256 .*/sha256 $SHA/" "prql-compiler.rb"`

**Comment by max-sixty** [comment]
Closing as completed!
